import "pkg:/source/utilities/utilities.bs"
import "pkg:/source/api/jamendoSDK.bs"


sub init()
    m.top.functionName = "getRadios"
end sub

sub getRadios()
    if not isAllValid([m.global.clientID, m.top.radioID]) then return

    params = {
        client_id: m.global.clientID,
        id: m.top.radioID,
        format: "json",
        limit: m.top.limit,
        offset: m.top.offset
    }

    m.top.responseBody = api.radios.get(params)
end sub
